use crate::notif::email::send_email;
use crate::server::user_control::check_role;
use crate::state::store::Store;
use crate::util::crypto::get_new_salt;
use crate::util::crypto::get_password_hash;
use crate::util::crypto::verify_password;
use isabelle_dm::data_model::item::Item;
use isabelle_dm::data_model::process_result::ProcessResult;
use log::{error, info};
use std::collections::HashMap;
