FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /root
ENV HOME="/root"

RUN apt-get update && \
    apt-get install -y build-essential \
                       curl \
                       docker.io \
                       git \
                       libssl-dev \
                       patchelf \
                       pkg-config

RUN /bin/bash -c "curl --proto '=https' --tlsv1.2 -sSf curl https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env && rustup update"

RUN chmod -R 777 /root

ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo install cross --git https://github.com/cross-rs/cross

RUN chmod -R 777 /root/.cargo
