FROM ubuntu:23.04

ARG DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /home/root
ENV HOME="/home/root"

RUN apt-get update && \
    apt-get install -y build-essential cargo curl git libssl-dev pkg-config

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN mkdir -p /home/root/.cargo && chmod -R 777 /home/root/.cargo

ENV PATH="/home/root/.cargo/bin:${PATH}"
